server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false
    username: root
    password: wang123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.90.128
    port: 5672
    username: wj
    password: 123
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo